modLoader = "aplp"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
mojo = "net.thesilkminer.mc.austin.rollsodrops.RollsODrops"
modId = "rolls-o-drops"
displayName = "Rolls o' Drops"
version = "${file.jarVersion}"
autors = "TheSilkMiner, N1Kx"

[[dependencies.rolls-o-drops]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rolls-o-drops]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
